roar:
  local_planner_manager_node:
    ros__parameters:
      manager:
        debug: true
        loop_rate: 1000.0
      use_sim_time: true

lifecycle_manager_local_planning:
  ros__parameters:
    autostart: true
    use_sim_time: true
    node_names: ["/roar/local_planner_manager_node"]
